DB_USERNAME=postgres
DB_PASSWORD=Vatika@220

JWT_SECRET=mysecretkeymysecretkeymysecretkey123456
GOOGLE_CLIENT_ID=1077449209828-ajb8mokkgvaacsbth1rp2t0757981g3l.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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

cloudinary.cloud-name=KnowledgeGap
cloudinary.api-key=663894938371783
cloudinary.api-secret=9_N7Dcdyq-VrKI5GnnI9UQkzxqA
app.cors.allowed-origin=http://localhost:5173