DB_USERNAME=postgres
DB_PASSWORD=Vatika@220

JWT_SECRET=mysecretkeymysecretkeymysecretkey123456
spring.security.oauth2.client.registration.google.client-id=1077449209828-ajb8mokkgvaacsbth1rp2t0757981g3l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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 

cloudinary.cloud-name=w1vrtpxe
cloudinary.api-key=464534188516223
cloudinary.api-secret=1LHt0ofVoz-JCr2sRGrJOb7dBsc
app.cors.allowed-origin=http://localhost:5173



